### ISSUE TITLE
Postcss dependencies are not watched

### ISSUE THREAD

**Issue by kuon** [g45t345rt/esbuild-style-plugin#3]
When in watch mode, if a postcss dependency is modified, it does not trigger a recompilation.

`esbuild-plugin-postcss2` handle this by parsing the output message of the postcss process

https://github.com/martonlederer/esbuild-plugin-postcss2/blob/3e61fd941e3ec950ceee0672a3ce4f834df0f6bd/src/index.ts#L283

**Comment by kuon** [comment]
My current workaround is to use `chokidar` to manually watch files with `esbuild`'s `watch` option disabled.

This setup might be better than using esbuild own `watch` function because `esbuild` uses polling.

This requires to pass dependencies to watch manually, but this is not a big issue.

I am not sure if this is worth supporting. If you decide not to support it, maybe mention in the README that it will not follow `postcss` dependencies.

**Comment by kuon** [comment]
I use tailwind with JIT, which in turn will watch `.html` files.

Here is my stack:

```
          require('postcss-import')({
            path: [
              path.join(__dirname, 'assets/css'),
              path.join(__dirname, 'assets')
            ]
          }),
          require('postcss-url')({ url: 'inline' }),
          require('postcss-nested'),
          require('autoprefixer'),
          require('tailwindcss')()
```

All to today's latest version.

**Comment by kuon** [comment]
No, I hardly ever use anything else. Tailwind has been my only real dependency for some times now.

**Comment by g45t345rt** [comment]
@kuon I have publish the code on npm, can you test and close the issue?
Thanks for reporting!

**Comment by kuon** [comment]
Sorry for the delay I was on other things. It seems to work fine. Cheers.
