### ISSUE TITLE
Is it prossible to set the build target to node12.x?

### ISSUE THREAD

**Issue by luhc228** [g45t345rt/esbuild-style-plugin#5]
Hi~. I'm using the `esbuild-style-plugin` package in my project. But when I ran the test in github action,  I got an error:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/44047106/160078362-f85310f0-7615-4279-ba62-b6628c4d3b99.png">

It seems that the `??` syntax in the `dist/index.js` is supported by the node12.

You can see more details in [here](https://github.com/ice-lab/ice-next/runs/5687612152?check_suite_focus=true). 

When I add `transformIgnorePatterns` to `jest.config.js` to use `babel-jest` to compile `esbuild-style-plugin`, I will get an error: 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/44047106/160080020-b8e005b3-2779-45e6-88c8-2f8ba7892f00.png">

It was out of memory. https://github.com/ice-lab/ice-next/runs/5688694852?check_suite_focus=true

Can you set the build target to node@12.x in your esbuild config when bundling the package? If you do, I don't need to add `transformIgnorePatterns` config to compile the `dist/index.js`.

For example: 
https://esbuild.github.io/getting-started/#bundling-for-node

**Comment by g45t345rt** [comment]
[nullish coalescing operator (??)](https://github.com/tc39/proposal-nullish-coalescing) is not supported in Node 12

Can you update your job worklflow to `node-version: 14.x` or latest?
https://github.com/ice-lab/ice-next/blob/718b0c6c7274df67ccc33319f9c8de6339fa6243/.github/workflows/ci.yml#L13

**Comment by luhc228** [comment]
> [nullish coalescing operator (??)](https://github.com/tc39/proposal-nullish-coalescing) is not supported in Node 12 https://node.green/#ES2020-features--nullish-coalescing-operator-----
> 
> Can you update your job workflow to `node-version: 14.x` or latest? https://github.com/ice-lab/ice-next/blob/718b0c6c7274df67ccc33319f9c8de6339fa6243/.github/workflows/ci.yml#L13

I don't want to update the `node-version` to 14.x in my job workflow beacause our framework needs to support 12.x. If I have set to 14.x, I will not found some problems when in node 12.x.

**Comment by g45t345rt** [comment]
Added support for node12.
Can you update to latest `1.4.1` and close the issue if its fixed.

Thanks!
