### ISSUE TITLE
css file path in node_modules is not handled

### ISSUE THREAD

**Issue by meikidd** [g45t345rt/esbuild-style-plugin#6]
Thank you for this nice plugin.

Not sure if I made it correctly, seems the css file path in node_modules is not handled.

I have `antd` in my project, so I have a `@import 'antd/dist/antd.css';` statement in my css code. I got below error when I integrate with esbuild-style-plugin.

It should load antd from `{project_root}/node_modules/antd/dist/antd.css` but instead it was looking for the file at  `{project_root}/src/antd/dist/antd.css`.

```
✘ [ERROR] [plugin esbuild-style-plugin] ENOENT: no such file or directory, 
open '/Users/meiqg/workspace/kakashi/src/antd/dist/antd.css'

    temp_stylePlugin:/var/folders/s4/x09j7tsx33785wbmr0048qth0000gp/T/2022226-90663-1pb8rd1.3fzz.css:1:8:
      1 │ @import 'antd/dist/antd.css';
        ╵         ~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/esbuild-style-plugin/dist/index.js:195:10:
      195 │     build.onLoad({ filter: /.*/, namespace: LOAD_STYLE_NAMESPACE }, onStyleLoad(options));
          ╵           ~~~~~~

    at setup (/Users/meiqg/workspace/kakashi/node_modules/esbuild-style-plugin/dist/index.js:195:11)
    at handlePlugins (/Users/meiqg/workspace/kakashi/node_modules/esbuild/lib/main.js:881:11)
```

<img width="893" alt="image" src="https://user-images.githubusercontent.com/376338/160237817-f0ca93fa-1970-472a-8a99-e39371e29dde.png">

**Comment by g45t345rt** [comment]
`resolve-file` is not checking `node_modules` :S 
I will publish a fix today thanks for reporting!

**Comment by g45t345rt** [comment]
I've push the fix `1.3.1` to npm. Can you update and close the issue if it is fixed :)

**Comment by meikidd** [comment]
@g45t345rt Thank you for you speedy response.

The error still happens to me if I import the antd css in a `css`/`scss` file. **However, if I move the import statement into `jsx`/`tsx`, it would work nicely.**

```
✘ [ERROR] Cannot import "stylePlugin:/Users/meiqg/workspace/kakashi/node_modules/antd/dist/antd.css" into a CSS file

    temp_stylePlugin:/var/folders/s4/x09j7tsx33785wbmr0048qth0000gp/T/2022227-99634-14tea1g.2aw1.css:1:8:
      1 │ @import 'antd/dist/antd.css';
        ╵         ~~~~~~~~~~~~~~~~~~~~
```
<img width="859" alt="image" src="https://user-images.githubusercontent.com/376338/160261153-36895d7e-cd5d-4db2-a65f-2a73972dc77c.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/376338/160261186-1dde2fbe-53ae-4cf4-a3c5-9ec1125670d3.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/376338/160261200-1b587c1f-5e28-41c5-a260-474097c61e18.png">

**Comment by g45t345rt** [comment]
Use postcss plugin to inline css within css https://github.com/postcss/postcss-import

```ts
import atImport from 'postcss-import'

stylePlugin({
   postcss: [atImport()]
})
```

**Comment by meikidd** [comment]
Thanks a lot
